AllCops:
  Exclude:
    - bin/**/*
    - db/migrate/**/*

Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/LineLength:
  Max: 120

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/ExponentialNotation:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Naming/FileName:
  Exclude:
    - "lib/*-*.rb"
